version: "3"
services:
  vehicules:
    hostname: "vehicules"
    image: vehicules/iot
    depends_on:
      - "mosquitto"
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    networks:
        - webnet
  mosquitto:
    hostname: "mosquitto"
    image: eclipse-mosquitto
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - webnet
  convertisseur:
    hostname: "convertisseur"
    image: convertisseur/iot
    depends_on:
      - "openfire"
      - "mosquitto"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - webnet
  openfire:
    hostname: "openfire"
    image: xmpp/iot
    ports:
      - "9090:9090"
      - "5222:5222"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - webnet
  xmppweb:
    hostname: "xmppweb"
    image: xmppweb/iot
    depends_on:
      - "web"
      - "openfire"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - webnet
  xmppbdd:
    hostname: "xmppbdd"
    image: xmppbdd/iot
    depends_on:
      - "couchdb"
      - "openfire"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
        - webnet
  couchdb:
    hostname: "couchdb"
    image: couchdb
    ports:
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - "COUCHDB_USER=admin"
      - "COUCHDB_PASSWORD=admin"
    networks:
        - webnet
  web:
    hostname: "web"
    image: flask/iot
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3678:80"
    networks:
      - webnet
networks:
  webnet:
#     driver: overlay